# -*- coding: utf-8 -*-
"""EXP_1 - RL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OPxpRVESa5XbQt2SsO1eOY3nSvQY-3Sk
"""

jkgp[kpip install git+https://github.com/mimoralea/gym-walk#egg=gym-walk

P = {

    0 : {
        0 : [(0.8 , 0 , 0.0 , False)],
        1 : [(0.6 , 0 , 0.0 , False)],
        2 : [(1.0 , 1 , 0.0 , False)]
    },

    1 : {
        0 : [(1.0 , 0 , 0.0 , False)],
        1 : [(1.0 , 4 , 0.0 , False)],
        2 : [(1.0 , 2 , 0.0 , False)]
    },

    2 : {
        0 : [(1.0 , 1 , 0.0 , False)],
        1 : [(0.8 , 2 , 0.0 , False)],
        2 : [(0.8 , 2 , 0.0 , False)]
    },

    3 : {
        0 : [(0.8 , 3 , 0.0 , False)],
        1 : [(0.8 , 3 , 0.0 , False)],
        2 : [(1.0 , 4 , 0.0 , False)]
    },
    4 : {
        0 : [(1.0 , 3 , 0.0 , False)],
        1 : [(1.0 , 6 , 1.0 , True)],
        2 : [(1.0 , 5 , 0.0 , False)]
    },
    5 : {
        0 : [(1.0 , 4 , 0.0 , False)],
        1 : [(0.8 , 5 , 0.0 , False)],
        2 : [(0.8 , 5 , 0.0 , False)]
    },
    6 : {
        0 : [(1.0 , 6 , 1.0 , True)],
        1 : [(1.0 , 6 , 1.0 , True)],
        2 : [(1.0 , 6 , 1.0 , True)]
    },
}

P